# Site settings
title: The Other Tim Duncan
description: Random ravings about software development, technology and life
author : Tim Duncan
url: http://TheOtherTimDuncan.com
gravatar_url: https://www.gravatar.com/avatar/562dd2ea62eb03c58432fd422b7f9e06
github_username:  TheOtherTimDuncan

twitter:
  username: TheOtherTDuncan
  
# Jekyll Settings
permalink: /archive/:title/
exclude: [vendor]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-seo-tag